### ISSUE TITLE
Technical Question - multi-zone deployment

### ISSUE THREAD

**Issue by shavidze** [RJPearson94/terraform-aws-open-next-examples#1]
Hi again, I can't understand some inputs we pass for multi-zone distribution:

```ts
zones = [{
    root = true
    name = "home"
    folder_path = "./home/.open-next"
  },{
    root = false
    name = "docs"
    folder_path = "./docs/.open-next"
}]
```

for example, what does it mean `root=true`, I have. just one build that I want to deploy on multi-zone with `SHARED_DISTRIBUTION_AND_BUCKET`, when I set `root=true`, what is it doing?

## P.S.
It would be very very nice, if we communicate for such kind questions in discord or somewhere, for future purpose it would be nice as well because if someone will have the same question maybe I will help them as well.

**Comment by RJPearson94** [comment]
Hi @shavidze,

I need to work on the documentation for both the module and examples. 

So the root zone is the next.js app that will be called when there is no matching path to another zone/ next.js app. 
For shared distribution configuration, if you make a request to `/docs/**`, you will be routed to the *docs* zone/ app, whereas if you make a request to `/`, `/blog`, etc., you will go to the *home* zone/ app. 
You can only have 1 root zone for the application.
In hindsight, default might have been a better name for this.

I don't currently have Discord due to the maintenance overhead of dealing with moderation and spam. Discord is also blocked in many corporate scenarios, so I don't want to limit discussions and issues to another channel. I will think/ look into this. I may try Github discussions in the first instance.

I hope this helps

**Comment by shavidze** [comment]
@RJPearson94 So, If I have just one application I will have 1 root zone?

**Comment by RJPearson94** [comment]
Hi @shavidze, you will always only have 1 zone marked as the root zone

For a single zone, you will have the following config

```
zones = [{
    root = true
    name = "<<zone name>>"
    folder_path = "<<path to app folder>>/.open-next"
  }]
```

If you add another zone, the zones variable will be updated to the following

```
zones = [{
    root = true
    name = "<<zone name>>"
    folder_path = "<<path to app folder>>/.open-next"
  },{
    root = false
    name = "<<additional zone name>>"
    folder_path = "<<path to additional app folder>>/.open-next"
}]
```

For 3 zones

```
zones = [{
    root = true
    name = "<<zone name>>"
    folder_path = "<<path to app folder>>/.open-next"
  },{
    root = false
    name = "<<additional zone name>>"
    folder_path = "<<path to additional app folder>>/.open-next"
},{
    root = false
    name = "<<additional zone 2 name>>"
    folder_path = "<<path to additional app 2 folder>>/.open-next"
}]
```

And so on for each zone you need.

**Comment by Saba-Shavidze** [comment]
So, zones should be specifies in case of single build as well. I understand wrong way your example app for multizone when u have 2 application deployed in multizone, I just want to deploy my single app in multizone, everything will be same in zones array excepts one property root will be true in one of them and for others false

**Comment by shavidze** [comment]
So, zones should be specified in case of single build as well. I understand wrong way your example app for multizone when u have 2 application deployed in multizone, I just want to deploy my single app in multizone, everything will be same in zones array excepts one property root will be true in one of them and for others false, something like this:

```ts
  zones = [
    {
      root        = true
      name        = "web-application"
      folder_path = "../.open-next"
    },
   {
      root        = false
      name        = "web-application"
      folder_path = "../.open-next"
    } ,
    {
      root        = false
      name        = "web-application"
      folder_path = "../.open-next"
   }

  ]
```

**Comment by RJPearson94** [comment]
As you only need a single zone, you will only need the following config

```
  zones = [{
      root        = true
      name        = "web-application"
      folder_path = "../.open-next"
    }]
```

This effectively is the same as using the single zone module. So a request to any path will be sent to the web-application next.js app.

Where the multi-zone module is useful, say you add another next.js app, i.e. blog. 

```
  zones = [{
      root        = true
      name        = "web-application"
      folder_path = "../.open-next"
    },{
      root        = false
      name        = "blog"
      folder_path = "../blog/.open-next"
    }]
``` 
The module can deploy both next.js apps to AWS. If you make a request to `/blog/**`, then the request will go to the newly added blog next.js app; requests to anything not matching that path will go to the web-application next.js app (the root zone)

**Comment by Saba-Shavidze** [comment]
Maybe I understand what you call zone wrong way, I thought it was a region's zone and my application content would be distributed on multizone, maybe I'm wrong with it?

**Comment by RJPearson94** [comment]
Ah, the zones terminology comes from next.js https://nextjs.org/docs/pages/building-your-application/deploying/multi-zones
It is effectively a way of having multiple next.js apps and present them as if they were 1.

The module doesn't currently support deploying to multiple regions. It has been something I have considered adding support for but I've not had a use case which needed multi-region until now. 
Feel free to open an issue on the Terraform module to add support for multi-region deployment

Sorry for the confusion.

**Comment by RJPearson94** [comment]
I think I misunderstood your last comment; I think you are talking about AWS availability zones.

As we use lambda, you don't need to specify the AZs. The lambda service runs across all available AZs in the region. If you just have a single next.js app to deploy you can use the single zone module

**Comment by RJPearson94** [comment]
If you do need to connect your lambda to a VPC, you do need to "specify subnets in multiple Availability Zones to ensure high availability" (from https://docs.aws.amazon.com/lambda/latest/dg/security-resilience.html)

**Comment by shavidze** [comment]
@RJPearson94 Thanks a lot for taking the time, Could you give me some suggestions about on-demand validation should I use a revalidation queue for it or directly revalidate the CDN?

**Comment by RJPearson94** [comment]
hi @shavidze, I need to do some reading on that. As I don't use that functionality. 
I believe that is why the revalidation queue, etc. was added but that question might be worth asking on the open next discord

**Comment by RJPearson94** [comment]
reading the open next docs, it mentions "When you manualy revalidates the Next.js cache for a specific page, the ISR cache files stored on S3 will be updated. However, it is still necessary to invalidate the CloudFront cache:" (from https://open-next.js.org/common_issues/isr#on-demand-revalidation) so you will have to manually invalidate the CloudFront distribution anyway

**Comment by RJPearson94** [comment]
The open-next maintainers decided not to auto-revalidate due to the cost. See https://discord.com/channels/983865673656705025/983865673656705028/1205470224867008564

**Comment by shavidze** [comment]
@RJPearson94 Thanks a lot for your effort and time for helping me, I really really appreciate it ❤️

**Comment by RJPearson94** [comment]
No problem @shavidze, glad I can help
