### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by zhavir** [RJPearson94/terraform-aws-open-next-examples#2]
## Technical Details
Seems like that the example, out of the box, is not working anymore

here the exception from cloudfront

2024-03-27T14:37:20.944Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'index'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

any suggestion? 

## Steps to Reproduce

reproducible by cloning this repo and by applying the listed command in the readme 

## Logs

Add logs of the error to help explain your problem.

**Comment by RJPearson94** [comment]
Hi @zhavir,

Which example were you trying to deploy?

**Comment by zhavir** [comment]
hello! single-zone

**Comment by RJPearson94** [comment]
Hey @zhavir,

Apologies for the slow response. I've not been able to replicate this.
The module defaults to deploying the lambda functions using node 20 and ARM. Can I check if you are using node 20 when running the build and are building the app on an ARM machine?
If you aren't using an ARM machine to build the app, you can set `function_architecture` to `x86_64` in the terragrunt.hcl

This may resolve your issue. If not, please let me know, and I can try to investigate further.

The example is out of date, so I'm going to update it anyway.

Kind Regards
Rob

**Comment by RJPearson94** [comment]
@zhavir did this resolve your issue?

**Comment by zhavir** [comment]
sorry, I decided to go with CDK directly. Anyway I have an Intel based macbook

**Comment by RJPearson94** [comment]
Ok no problem @zhavir. I’m going to close this issue, feel free to repo if you try the module again and encounter the same issue
